CREATE TABLE POST (
  POST_ID NUMBER,
  CONSTRAINT POST_PK PRIMARY KEY (POST_ID),
  MESSAGE NVARCHAR2(1000),
  DATE_POSTED TIMESTAMP(6) WITH TIME ZONE,
  USER_POSTED NUMBER,
  CONSTRAINT USER_POSTED_FK FOREIGN KEY (USER_POSTED) REFERENCES USER_SOCIAL (USER_ID)
  );