CREATE SEQUENCE USER_SOCIAL_ID_SEQ MINVALUE 1 MAXVALUE 50000 START WITH 1 INCREMENT BY 2;
CREATE SEQUENCE MESSAGE_ID_SEQ MINVALUE 1 MAXVALUE 50000 START WITH 1 INCREMENT BY 2;
CREATE SEQUENCE POST_ID_SEQ MINVALUE 1 MAXVALUE 50000 START WITH 1 INCREMENT BY 2;